# Generated by Django 5.0.3 on 2024-03-13 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics/cast_img')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HomeMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('release_date', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pics/home_img')),
                ('youtube_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PopularMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pics/popular_movies_img')),
                ('youtube_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pics/upcoming_movies_img')),
                ('youtube_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AddMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('poster_img', models.ImageField(upload_to='pics/added_movies_img')),
                ('description', models.TextField()),
                ('release_date', models.CharField(max_length=130)),
                ('youtube_link', models.URLField()),
                ('duration', models.CharField(max_length=130)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('casts', models.ManyToManyField(related_name='movies', to='movieshallapp.cast')),
                ('genre', models.ManyToManyField(related_name='movies', to='movieshallapp.genre')),
            ],
        ),
    ]
