# Generated by Django 5.0.3 on 2024-03-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieshallapp', '0005_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmovies',
            name='director_name',
            field=models.CharField(default='chidambaram', max_length=130),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addmovies',
            name='description',
            field=models.CharField(max_length=130),
        ),
    ]
