# Generated by Django 5.0.3 on 2024-03-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieshallapp', '0006_addmovies_director_name_alter_addmovies_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingmovies',
            name='release_date',
            field=models.CharField(default='abcd', max_length=250),
            preserve_default=False,
        ),
    ]
