# Generated by Django 5.0.3 on 2024-03-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('profile_img', models.ImageField(upload_to='pics/user_img')),
                ('password', models.CharField(max_length=35)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
